# Generated by Django 5.2.15 on 2026-06-25 01:28

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('published_year', models.SmallIntegerField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('search_vector', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sort_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='idx_author_name'), models.Index(fields=['sort_name'], name='idx_author_sort_name')],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('illustrator', 'Illustrator')], default='author', max_length=50, null=True)),
                ('position', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='books.BookAuthor', to='books.author'),
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('source', models.CharField(choices=[('open_library', 'Open Library'), ('user', 'User')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='idx_genre_slug'), models.Index(fields=['name'], name='idx_genre_name')],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, through='books.BookGenre', to='books.genre'),
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('reading', 'Currently Reading'), ('finished', 'Finished'), ('paused', 'Paused'), ('abandoned', 'DNF')], default='not_started', max_length=20)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_percent', models.SmallIntegerField(blank=True, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('read_count', models.SmallIntegerField(default=0)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_on', models.DateField(default=django.utils.timezone.localdate)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_percent', models.SmallIntegerField(blank=True, null=True)),
                ('pages_read', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=280, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book')),
                ('reading_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='books.readinglog')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='BookshelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_items', to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_items', to='books.shelf')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['book'], name='idx_bookauthor_book'),
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['author'], name='idx_bookauthor_author'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author', 'role'), name='books_bookauthor_book_author_role_uniq'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['book'], name='idx_bookgenre_book'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['genre'], name='idx_bookgenre_genre'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='books_bookgenre_book_genre_uniq'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='idx_book_created'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['-created_at'], name='idx_book_active'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_13__isnull', False)), fields=('isbn_13',), name='idx_book_isbn_13'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_10__isnull', False)), fields=('isbn_10',), name='idx_book_isbn_10'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['book'], name='idx_reading_book'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['status'], name='idx_reading_status'),
        ),
        migrations.AddConstraint(
            model_name='readinglog',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__isnull', True), models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), _connector='OR'), name='books_readinglog_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['reading_log'], name='idx_progress_log'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['book', 'logged_on'], name='idx_progress_book_date'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['logged_on'], name='idx_progress_logged_on'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__isnull', True), models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), _connector='OR'), name='books_readingprogress_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='idx_review_book'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='books_review_rating_range'),
        ),
        migrations.AddIndex(
            model_name='bookshelfitem',
            index=models.Index(fields=['book'], name='idx_bsi_book'),
        ),
        migrations.AddIndex(
            model_name='bookshelfitem',
            index=models.Index(fields=['shelf'], name='idx_bsi_shelf'),
        ),
        migrations.AddConstraint(
            model_name='bookshelfitem',
            constraint=models.UniqueConstraint(fields=('book', 'shelf'), name='books_bookshelfitem_book_shelf_uniq'),
        ),
    ]
