# Generated by Django 5.2.15 on 2026-06-26 15:53

import books.models
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('subtitle', models.CharField(blank=True, max_length=500, null=True)),
                ('isbn_13', models.CharField(blank=True, max_length=13, null=True)),
                ('isbn_10', models.CharField(blank=True, max_length=10, null=True)),
                ('pages', models.PositiveIntegerField(blank=True, null=True)),
                ('published_year', models.SmallIntegerField(blank=True, null=True)),
                ('published_date', models.DateField(blank=True, null=True)),
                ('publisher', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('cover_url', models.URLField(blank=True, max_length=2000, null=True)),
                ('cover_image', models.FileField(blank=True, upload_to=books.models.cover_upload_path)),
                ('openlibrary_work_id', models.CharField(blank=True, max_length=64, null=True)),
                ('openlibrary_edition_key', models.CharField(blank=True, max_length=64, null=True)),
                ('google_books_id', models.CharField(blank=True, max_length=64, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=10)),
                ('format', models.CharField(blank=True, choices=[('physical', 'Physical'), ('ebook', 'Ebook'), ('audiobook', 'Audiobook')], default='physical', max_length=20)),
                ('owned', models.BooleanField(default=False)),
                ('narrator', models.CharField(blank=True, max_length=500, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('series_position', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('search_vector', models.TextField(blank=True, editable=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ReadingGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveSmallIntegerField(unique=True)),
                ('target_books', models.PositiveSmallIntegerField()),
                ('target_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='Shelf',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WebhookEndpoint',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('url', models.URLField(max_length=2000)),
                ('secret', models.CharField(max_length=128)),
                ('events', models.JSONField(blank=True, default=list)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('sort_name', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='idx_author_name'), models.Index(fields=['sort_name'], name='idx_author_sort_name')],
            },
        ),
        migrations.CreateModel(
            name='BookAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, choices=[('author', 'Author'), ('editor', 'Editor'), ('translator', 'Translator'), ('illustrator', 'Illustrator')], default='author', max_length=50, null=True)),
                ('position', models.SmallIntegerField(default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_authors', to='books.book')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(through='books.BookAuthor', to='books.author'),
        ),
        migrations.CreateModel(
            name='BookNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='private_notes', to='books.book')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('source', models.CharField(choices=[('open_library', 'Open Library'), ('user', 'User')], default='user', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['slug'], name='idx_genre_slug'), models.Index(fields=['name'], name='idx_genre_name')],
            },
        ),
        migrations.CreateModel(
            name='BookGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.book')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_genres', to='books.genre')),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='genres',
            field=models.ManyToManyField(blank=True, through='books.BookGenre', to='books.genre'),
        ),
        migrations.CreateModel(
            name='ImportJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('isbns', 'ISBNs'), ('goodreads_csv', 'Goodreads CSV'), ('storygraph_csv', 'StoryGraph CSV'), ('metadata_backfill', 'Metadata backfill')], max_length=20)),
                ('status', models.CharField(choices=[('awaiting_confirmation', 'Awaiting confirmation'), ('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=24)),
                ('csv_file', models.FileField(blank=True, upload_to=books.models.import_job_upload_path)),
                ('isbns', models.JSONField(blank=True, default=list)),
                ('book_ids', models.JSONField(blank=True, default=list)),
                ('preview', models.JSONField(blank=True, default=list)),
                ('progress_done', models.PositiveIntegerField(default=0)),
                ('progress_total', models.PositiveIntegerField(default=0)),
                ('result', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MetadataMatchProposal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('candidate', models.JSONField(default=dict)),
                ('score', models.FloatField(default=0.0)),
                ('alternates', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], default='pending', max_length=16)),
                ('source_summary', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metadata_proposals', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('position', models.CharField(blank=True, help_text='Page number or percent position in the book.', max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes', to='books.book')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReadingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('not_started', 'Want to Read'), ('reading', 'Currently Reading'), ('finished', 'Read'), ('paused', 'Paused'), ('abandoned', 'DNF')], default='not_started', max_length=20)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_percent', models.SmallIntegerField(blank=True, null=True)),
                ('total_pages', models.PositiveIntegerField(blank=True, null=True)),
                ('read_count', models.SmallIntegerField(default=0)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reading_log', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReadingProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_on', models.DateField(default=django.utils.timezone.localdate)),
                ('current_page', models.PositiveIntegerField(blank=True, null=True)),
                ('progress_percent', models.SmallIntegerField(blank=True, null=True)),
                ('pages_read', models.PositiveIntegerField(blank=True, null=True)),
                ('note', models.CharField(blank=True, max_length=280, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reading_progress', to='books.book')),
                ('reading_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_entries', to='books.readinglog')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('sort_order', models.SmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'series',
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['slug'], name='idx_series_slug'), models.Index(fields=['name'], name='idx_series_name')],
            },
        ),
        migrations.AddField(
            model_name='book',
            name='series',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='books.series'),
        ),
        migrations.CreateModel(
            name='BookshelfItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_items', to='books.book')),
                ('shelf', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookshelf_items', to='books.shelf')),
            ],
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['book'], name='idx_bookauthor_book'),
        ),
        migrations.AddIndex(
            model_name='bookauthor',
            index=models.Index(fields=['author'], name='idx_bookauthor_author'),
        ),
        migrations.AddConstraint(
            model_name='bookauthor',
            constraint=models.UniqueConstraint(fields=('book', 'author', 'role'), name='books_bookauthor_book_author_role_uniq'),
        ),
        migrations.AddIndex(
            model_name='booknote',
            index=models.Index(fields=['book'], name='idx_booknote_book'),
        ),
        migrations.AddConstraint(
            model_name='booknote',
            constraint=models.UniqueConstraint(fields=('book',), name='books_booknote_book_uniq'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['book'], name='idx_bookgenre_book'),
        ),
        migrations.AddIndex(
            model_name='bookgenre',
            index=models.Index(fields=['genre'], name='idx_bookgenre_genre'),
        ),
        migrations.AddConstraint(
            model_name='bookgenre',
            constraint=models.UniqueConstraint(fields=('book', 'genre'), name='books_bookgenre_book_genre_uniq'),
        ),
        migrations.AddIndex(
            model_name='importjob',
            index=models.Index(fields=['status', 'created_at'], name='idx_importjob_status'),
        ),
        migrations.AddIndex(
            model_name='metadatamatchproposal',
            index=models.Index(fields=['status', '-created_at'], name='idx_metadata_proposal_status'),
        ),
        migrations.AddConstraint(
            model_name='metadatamatchproposal',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('book',), name='uniq_pending_metadata_proposal_per_book'),
        ),
        migrations.AddIndex(
            model_name='quote',
            index=models.Index(fields=['book'], name='idx_quote_book'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['book'], name='idx_reading_book'),
        ),
        migrations.AddIndex(
            model_name='readinglog',
            index=models.Index(fields=['status'], name='idx_reading_status'),
        ),
        migrations.AddConstraint(
            model_name='readinglog',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__isnull', True), models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), _connector='OR'), name='books_readinglog_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['reading_log'], name='idx_progress_log'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['book', 'logged_on'], name='idx_progress_book_date'),
        ),
        migrations.AddIndex(
            model_name='readingprogress',
            index=models.Index(fields=['logged_on'], name='idx_progress_logged_on'),
        ),
        migrations.AddConstraint(
            model_name='readingprogress',
            constraint=models.CheckConstraint(condition=models.Q(('progress_percent__isnull', True), models.Q(('progress_percent__gte', 0), ('progress_percent__lte', 100)), _connector='OR'), name='books_readingprogress_progress_percent_range'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['book'], name='idx_review_book'),
        ),
        migrations.AddConstraint(
            model_name='review',
            constraint=models.CheckConstraint(condition=models.Q(('rating__isnull', True), models.Q(('rating__gte', 1), ('rating__lte', 5)), _connector='OR'), name='books_review_rating_range'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-created_at'], name='idx_book_created'),
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(condition=models.Q(('deleted_at__isnull', True)), fields=['-created_at'], name='idx_book_active'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_13__isnull', False)), fields=('isbn_13',), name='idx_book_isbn_13'),
        ),
        migrations.AddConstraint(
            model_name='book',
            constraint=models.UniqueConstraint(condition=models.Q(('isbn_10__isnull', False)), fields=('isbn_10',), name='idx_book_isbn_10'),
        ),
        migrations.AddIndex(
            model_name='bookshelfitem',
            index=models.Index(fields=['book'], name='idx_bsi_book'),
        ),
        migrations.AddIndex(
            model_name='bookshelfitem',
            index=models.Index(fields=['shelf'], name='idx_bsi_shelf'),
        ),
        migrations.AddConstraint(
            model_name='bookshelfitem',
            constraint=models.UniqueConstraint(fields=('book', 'shelf'), name='books_bookshelfitem_book_shelf_uniq'),
        ),
    ]
