# Generated by Django 5.2.15 on 2026-06-25 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_import_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='readinglog',
            name='status',
            field=models.CharField(choices=[('not_started', 'Want to Read'), ('reading', 'Currently Reading'), ('finished', 'Read'), ('paused', 'Paused'), ('abandoned', 'DNF')], default='not_started', max_length=20),
        ),
    ]
