# Generated by Django 5.2.15 on 2026-06-27 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_batch9_ux_roadmap'),
    ]

    operations = [
        migrations.AlterField(
            model_name='importjob',
            name='kind',
            field=models.CharField(choices=[('isbns', 'ISBNs'), ('goodreads_csv', 'Goodreads CSV'), ('storygraph_csv', 'StoryGraph CSV'), ('metadata_backfill', 'Metadata backfill'), ('metadata_refresh', 'Metadata refresh')], max_length=20),
        ),
    ]
